// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/stores.go -package=mocks TeamStore TeamInvitationStore TeamRegistryStore TeamCredentialStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	onprem "github.com/pax-beehive/pax-nexus/internal/deployment/onprem"
	saas "github.com/pax-beehive/pax-nexus/internal/deployment/saas"
	gomock "go.uber.org/mock/gomock"
)

// MockTeamStore is a mock of TeamStore interface.
type MockTeamStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamStoreMockRecorder
	isgomock struct{}
}

// MockTeamStoreMockRecorder is the mock recorder for MockTeamStore.
type MockTeamStoreMockRecorder struct {
	mock *MockTeamStore
}

// NewMockTeamStore creates a new mock instance.
func NewMockTeamStore(ctrl *gomock.Controller) *MockTeamStore {
	mock := &MockTeamStore{ctrl: ctrl}
	mock.recorder = &MockTeamStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamStore) EXPECT() *MockTeamStoreMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockTeamStore) CreateTeam(ctx context.Context, team saas.Team, ownerMembershipID, idempotencyKey string, now time.Time) (saas.Team, onprem.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, team, ownerMembershipID, idempotencyKey, now)
	ret0, _ := ret[0].(saas.Team)
	ret1, _ := ret[1].(onprem.Member)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamStoreMockRecorder) CreateTeam(ctx, team, ownerMembershipID, idempotencyKey, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamStore)(nil).CreateTeam), ctx, team, ownerMembershipID, idempotencyKey, now)
}

// CreateUserSession mocks base method.
func (m *MockTeamStore) CreateUserSession(ctx context.Context, identity onprem.ExternalIdentity, record saas.TeamSessionRecord) (onprem.HumanPrincipal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserSession", ctx, identity, record)
	ret0, _ := ret[0].(onprem.HumanPrincipal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserSession indicates an expected call of CreateUserSession.
func (mr *MockTeamStoreMockRecorder) CreateUserSession(ctx, identity, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserSession", reflect.TypeOf((*MockTeamStore)(nil).CreateUserSession), ctx, identity, record)
}

// GetAuditEvent mocks base method.
func (m *MockTeamStore) GetAuditEvent(ctx context.Context, teamID string, auditEventID int64) (onprem.AuditEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuditEvent", ctx, teamID, auditEventID)
	ret0, _ := ret[0].(onprem.AuditEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuditEvent indicates an expected call of GetAuditEvent.
func (mr *MockTeamStoreMockRecorder) GetAuditEvent(ctx, teamID, auditEventID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuditEvent", reflect.TypeOf((*MockTeamStore)(nil).GetAuditEvent), ctx, teamID, auditEventID)
}

// GetMember mocks base method.
func (m *MockTeamStore) GetMember(ctx context.Context, teamID, membershipID string) (onprem.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMember", ctx, teamID, membershipID)
	ret0, _ := ret[0].(onprem.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMember indicates an expected call of GetMember.
func (mr *MockTeamStoreMockRecorder) GetMember(ctx, teamID, membershipID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMember", reflect.TypeOf((*MockTeamStore)(nil).GetMember), ctx, teamID, membershipID)
}

// GetTeam mocks base method.
func (m *MockTeamStore) GetTeam(ctx context.Context, teamID string) (saas.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamID)
	ret0, _ := ret[0].(saas.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamStoreMockRecorder) GetTeam(ctx, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeamStore)(nil).GetTeam), ctx, teamID)
}

// ListAuditEvents mocks base method.
func (m *MockTeamStore) ListAuditEvents(ctx context.Context, teamID string, filter onprem.AuditFilter) ([]onprem.AuditEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAuditEvents", ctx, teamID, filter)
	ret0, _ := ret[0].([]onprem.AuditEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAuditEvents indicates an expected call of ListAuditEvents.
func (mr *MockTeamStoreMockRecorder) ListAuditEvents(ctx, teamID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAuditEvents", reflect.TypeOf((*MockTeamStore)(nil).ListAuditEvents), ctx, teamID, filter)
}

// ListMembers mocks base method.
func (m *MockTeamStore) ListMembers(ctx context.Context, teamID string, filter onprem.MemberFilter) ([]onprem.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMembers", ctx, teamID, filter)
	ret0, _ := ret[0].([]onprem.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListMembers indicates an expected call of ListMembers.
func (mr *MockTeamStoreMockRecorder) ListMembers(ctx, teamID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMembers", reflect.TypeOf((*MockTeamStore)(nil).ListMembers), ctx, teamID, filter)
}

// ListTeamSummaries mocks base method.
func (m *MockTeamStore) ListTeamSummaries(ctx context.Context, userID string) ([]saas.TeamSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeamSummaries", ctx, userID)
	ret0, _ := ret[0].([]saas.TeamSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTeamSummaries indicates an expected call of ListTeamSummaries.
func (mr *MockTeamStoreMockRecorder) ListTeamSummaries(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeamSummaries", reflect.TypeOf((*MockTeamStore)(nil).ListTeamSummaries), ctx, userID)
}

// ResolveSession mocks base method.
func (m *MockTeamStore) ResolveSession(ctx context.Context, sessionID string, digest onprem.Digest, now time.Time) (onprem.HumanPrincipal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSession", ctx, sessionID, digest, now)
	ret0, _ := ret[0].(onprem.HumanPrincipal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSession indicates an expected call of ResolveSession.
func (mr *MockTeamStoreMockRecorder) ResolveSession(ctx, sessionID, digest, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSession", reflect.TypeOf((*MockTeamStore)(nil).ResolveSession), ctx, sessionID, digest, now)
}

// RevokeSession mocks base method.
func (m *MockTeamStore) RevokeSession(ctx context.Context, sessionID string, digest onprem.Digest, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeSession", ctx, sessionID, digest, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeSession indicates an expected call of RevokeSession.
func (mr *MockTeamStoreMockRecorder) RevokeSession(ctx, sessionID, digest, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeSession", reflect.TypeOf((*MockTeamStore)(nil).RevokeSession), ctx, sessionID, digest, now)
}

// SwitchTeam mocks base method.
func (m *MockTeamStore) SwitchTeam(ctx context.Context, sessionID, userID, teamID string, now time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SwitchTeam", ctx, sessionID, userID, teamID, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// SwitchTeam indicates an expected call of SwitchTeam.
func (mr *MockTeamStoreMockRecorder) SwitchTeam(ctx, sessionID, userID, teamID, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SwitchTeam", reflect.TypeOf((*MockTeamStore)(nil).SwitchTeam), ctx, sessionID, userID, teamID, now)
}

// UpdateMember mocks base method.
func (m *MockTeamStore) UpdateMember(ctx context.Context, teamID, actorMembershipID string, member onprem.Member, now time.Time) (onprem.Member, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMember", ctx, teamID, actorMembershipID, member, now)
	ret0, _ := ret[0].(onprem.Member)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateMember indicates an expected call of UpdateMember.
func (mr *MockTeamStoreMockRecorder) UpdateMember(ctx, teamID, actorMembershipID, member, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMember", reflect.TypeOf((*MockTeamStore)(nil).UpdateMember), ctx, teamID, actorMembershipID, member, now)
}

// MockTeamInvitationStore is a mock of TeamInvitationStore interface.
type MockTeamInvitationStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamInvitationStoreMockRecorder
	isgomock struct{}
}

// MockTeamInvitationStoreMockRecorder is the mock recorder for MockTeamInvitationStore.
type MockTeamInvitationStoreMockRecorder struct {
	mock *MockTeamInvitationStore
}

// NewMockTeamInvitationStore creates a new mock instance.
func NewMockTeamInvitationStore(ctrl *gomock.Controller) *MockTeamInvitationStore {
	mock := &MockTeamInvitationStore{ctrl: ctrl}
	mock.recorder = &MockTeamInvitationStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamInvitationStore) EXPECT() *MockTeamInvitationStoreMockRecorder {
	return m.recorder
}

// AcceptInvitation mocks base method.
func (m *MockTeamInvitationStore) AcceptInvitation(ctx context.Context, invitationPublicID string, digest onprem.Digest, userID, email string, emailVerified bool, idempotencyKey string, now time.Time) (onprem.HumanPrincipal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcceptInvitation", ctx, invitationPublicID, digest, userID, email, emailVerified, idempotencyKey, now)
	ret0, _ := ret[0].(onprem.HumanPrincipal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AcceptInvitation indicates an expected call of AcceptInvitation.
func (mr *MockTeamInvitationStoreMockRecorder) AcceptInvitation(ctx, invitationPublicID, digest, userID, email, emailVerified, idempotencyKey, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcceptInvitation", reflect.TypeOf((*MockTeamInvitationStore)(nil).AcceptInvitation), ctx, invitationPublicID, digest, userID, email, emailVerified, idempotencyKey, now)
}

// CreateInvitation mocks base method.
func (m *MockTeamInvitationStore) CreateInvitation(ctx context.Context, teamID string, record onprem.InvitationRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInvitation", ctx, teamID, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInvitation indicates an expected call of CreateInvitation.
func (mr *MockTeamInvitationStoreMockRecorder) CreateInvitation(ctx, teamID, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInvitation", reflect.TypeOf((*MockTeamInvitationStore)(nil).CreateInvitation), ctx, teamID, record)
}

// ListInvitations mocks base method.
func (m *MockTeamInvitationStore) ListInvitations(ctx context.Context, teamID string, filter onprem.InvitationFilter, now time.Time) ([]onprem.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInvitations", ctx, teamID, filter, now)
	ret0, _ := ret[0].([]onprem.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInvitations indicates an expected call of ListInvitations.
func (mr *MockTeamInvitationStoreMockRecorder) ListInvitations(ctx, teamID, filter, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInvitations", reflect.TypeOf((*MockTeamInvitationStore)(nil).ListInvitations), ctx, teamID, filter, now)
}

// RevokeInvitation mocks base method.
func (m *MockTeamInvitationStore) RevokeInvitation(ctx context.Context, teamID, invitationID, actorMembershipID string, canRevokeAdmin bool, now time.Time) (onprem.Invitation, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeInvitation", ctx, teamID, invitationID, actorMembershipID, canRevokeAdmin, now)
	ret0, _ := ret[0].(onprem.Invitation)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeInvitation indicates an expected call of RevokeInvitation.
func (mr *MockTeamInvitationStoreMockRecorder) RevokeInvitation(ctx, teamID, invitationID, actorMembershipID, canRevokeAdmin, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeInvitation", reflect.TypeOf((*MockTeamInvitationStore)(nil).RevokeInvitation), ctx, teamID, invitationID, actorMembershipID, canRevokeAdmin, now)
}

// MockTeamRegistryStore is a mock of TeamRegistryStore interface.
type MockTeamRegistryStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamRegistryStoreMockRecorder
	isgomock struct{}
}

// MockTeamRegistryStoreMockRecorder is the mock recorder for MockTeamRegistryStore.
type MockTeamRegistryStoreMockRecorder struct {
	mock *MockTeamRegistryStore
}

// NewMockTeamRegistryStore creates a new mock instance.
func NewMockTeamRegistryStore(ctrl *gomock.Controller) *MockTeamRegistryStore {
	mock := &MockTeamRegistryStore{ctrl: ctrl}
	mock.recorder = &MockTeamRegistryStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamRegistryStore) EXPECT() *MockTeamRegistryStoreMockRecorder {
	return m.recorder
}

// CreateAgent mocks base method.
func (m *MockTeamRegistryStore) CreateAgent(ctx context.Context, teamID string, profile onprem.AgentProfile) (onprem.AgentProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAgent", ctx, teamID, profile)
	ret0, _ := ret[0].(onprem.AgentProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAgent indicates an expected call of CreateAgent.
func (mr *MockTeamRegistryStoreMockRecorder) CreateAgent(ctx, teamID, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAgent", reflect.TypeOf((*MockTeamRegistryStore)(nil).CreateAgent), ctx, teamID, profile)
}

// GetOwnedAgent mocks base method.
func (m *MockTeamRegistryStore) GetOwnedAgent(ctx context.Context, teamID, membershipID, agentID string) (onprem.AgentProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnedAgent", ctx, teamID, membershipID, agentID)
	ret0, _ := ret[0].(onprem.AgentProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnedAgent indicates an expected call of GetOwnedAgent.
func (mr *MockTeamRegistryStoreMockRecorder) GetOwnedAgent(ctx, teamID, membershipID, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnedAgent", reflect.TypeOf((*MockTeamRegistryStore)(nil).GetOwnedAgent), ctx, teamID, membershipID, agentID)
}

// ListOwnedAgents mocks base method.
func (m *MockTeamRegistryStore) ListOwnedAgents(ctx context.Context, teamID, membershipID string, filter onprem.AgentFilter) ([]onprem.AgentProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOwnedAgents", ctx, teamID, membershipID, filter)
	ret0, _ := ret[0].([]onprem.AgentProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOwnedAgents indicates an expected call of ListOwnedAgents.
func (mr *MockTeamRegistryStoreMockRecorder) ListOwnedAgents(ctx, teamID, membershipID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOwnedAgents", reflect.TypeOf((*MockTeamRegistryStore)(nil).ListOwnedAgents), ctx, teamID, membershipID, filter)
}

// RetireOwnedAgent mocks base method.
func (m *MockTeamRegistryStore) RetireOwnedAgent(ctx context.Context, teamID, membershipID string, actor onprem.HumanPrincipal, agentID string, resourceVersion int64, idempotencyKey string, now time.Time) (onprem.AgentProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RetireOwnedAgent", ctx, teamID, membershipID, actor, agentID, resourceVersion, idempotencyKey, now)
	ret0, _ := ret[0].(onprem.AgentProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RetireOwnedAgent indicates an expected call of RetireOwnedAgent.
func (mr *MockTeamRegistryStoreMockRecorder) RetireOwnedAgent(ctx, teamID, membershipID, actor, agentID, resourceVersion, idempotencyKey, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RetireOwnedAgent", reflect.TypeOf((*MockTeamRegistryStore)(nil).RetireOwnedAgent), ctx, teamID, membershipID, actor, agentID, resourceVersion, idempotencyKey, now)
}

// UpdateOwnedAgent mocks base method.
func (m *MockTeamRegistryStore) UpdateOwnedAgent(ctx context.Context, teamID, membershipID string, actor onprem.HumanPrincipal, profile onprem.AgentProfile) (onprem.AgentProfile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOwnedAgent", ctx, teamID, membershipID, actor, profile)
	ret0, _ := ret[0].(onprem.AgentProfile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOwnedAgent indicates an expected call of UpdateOwnedAgent.
func (mr *MockTeamRegistryStoreMockRecorder) UpdateOwnedAgent(ctx, teamID, membershipID, actor, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOwnedAgent", reflect.TypeOf((*MockTeamRegistryStore)(nil).UpdateOwnedAgent), ctx, teamID, membershipID, actor, profile)
}

// MockTeamCredentialStore is a mock of TeamCredentialStore interface.
type MockTeamCredentialStore struct {
	ctrl     *gomock.Controller
	recorder *MockTeamCredentialStoreMockRecorder
	isgomock struct{}
}

// MockTeamCredentialStoreMockRecorder is the mock recorder for MockTeamCredentialStore.
type MockTeamCredentialStoreMockRecorder struct {
	mock *MockTeamCredentialStore
}

// NewMockTeamCredentialStore creates a new mock instance.
func NewMockTeamCredentialStore(ctrl *gomock.Controller) *MockTeamCredentialStore {
	mock := &MockTeamCredentialStore{ctrl: ctrl}
	mock.recorder = &MockTeamCredentialStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamCredentialStore) EXPECT() *MockTeamCredentialStoreMockRecorder {
	return m.recorder
}

// CreateDeviceEnrollment mocks base method.
func (m *MockTeamCredentialStore) CreateDeviceEnrollment(ctx context.Context, teamID, membershipID string, record onprem.EnrollmentRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeviceEnrollment", ctx, teamID, membershipID, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDeviceEnrollment indicates an expected call of CreateDeviceEnrollment.
func (mr *MockTeamCredentialStoreMockRecorder) CreateDeviceEnrollment(ctx, teamID, membershipID, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeviceEnrollment", reflect.TypeOf((*MockTeamCredentialStore)(nil).CreateDeviceEnrollment), ctx, teamID, membershipID, record)
}

// CreateOwnedEnrollment mocks base method.
func (m *MockTeamCredentialStore) CreateOwnedEnrollment(ctx context.Context, teamID, membershipID string, record onprem.EnrollmentRecord) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOwnedEnrollment", ctx, teamID, membershipID, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOwnedEnrollment indicates an expected call of CreateOwnedEnrollment.
func (mr *MockTeamCredentialStoreMockRecorder) CreateOwnedEnrollment(ctx, teamID, membershipID, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOwnedEnrollment", reflect.TypeOf((*MockTeamCredentialStore)(nil).CreateOwnedEnrollment), ctx, teamID, membershipID, record)
}

// ExchangeEnrollment mocks base method.
func (m *MockTeamCredentialStore) ExchangeEnrollment(ctx context.Context, enrollmentID string, digest onprem.Digest, credential onprem.CredentialRecord, now time.Time) (onprem.EnrollmentRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeEnrollment", ctx, enrollmentID, digest, credential, now)
	ret0, _ := ret[0].(onprem.EnrollmentRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeEnrollment indicates an expected call of ExchangeEnrollment.
func (mr *MockTeamCredentialStoreMockRecorder) ExchangeEnrollment(ctx, enrollmentID, digest, credential, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeEnrollment", reflect.TypeOf((*MockTeamCredentialStore)(nil).ExchangeEnrollment), ctx, enrollmentID, digest, credential, now)
}

// GetDevice mocks base method.
func (m *MockTeamCredentialStore) GetDevice(ctx context.Context, teamID, credentialID string) (onprem.DeviceDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDevice", ctx, teamID, credentialID)
	ret0, _ := ret[0].(onprem.DeviceDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDevice indicates an expected call of GetDevice.
func (mr *MockTeamCredentialStoreMockRecorder) GetDevice(ctx, teamID, credentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDevice", reflect.TypeOf((*MockTeamCredentialStore)(nil).GetDevice), ctx, teamID, credentialID)
}

// ListDeviceProvisionedAgents mocks base method.
func (m *MockTeamCredentialStore) ListDeviceProvisionedAgents(ctx context.Context, teamID, deviceCredentialID string) ([]onprem.DeviceProvisionedAgent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeviceProvisionedAgents", ctx, teamID, deviceCredentialID)
	ret0, _ := ret[0].([]onprem.DeviceProvisionedAgent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeviceProvisionedAgents indicates an expected call of ListDeviceProvisionedAgents.
func (mr *MockTeamCredentialStoreMockRecorder) ListDeviceProvisionedAgents(ctx, teamID, deviceCredentialID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeviceProvisionedAgents", reflect.TypeOf((*MockTeamCredentialStore)(nil).ListDeviceProvisionedAgents), ctx, teamID, deviceCredentialID)
}

// ListDevices mocks base method.
func (m *MockTeamCredentialStore) ListDevices(ctx context.Context, teamID string, filter onprem.DeviceFilter) ([]onprem.DeviceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDevices", ctx, teamID, filter)
	ret0, _ := ret[0].([]onprem.DeviceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDevices indicates an expected call of ListDevices.
func (mr *MockTeamCredentialStoreMockRecorder) ListDevices(ctx, teamID, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDevices", reflect.TypeOf((*MockTeamCredentialStore)(nil).ListDevices), ctx, teamID, filter)
}

// ListExpiringEnrollments mocks base method.
func (m *MockTeamCredentialStore) ListExpiringEnrollments(ctx context.Context, teamID string, before time.Time, limit int) ([]onprem.AgentEnrollmentMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiringEnrollments", ctx, teamID, before, limit)
	ret0, _ := ret[0].([]onprem.AgentEnrollmentMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiringEnrollments indicates an expected call of ListExpiringEnrollments.
func (mr *MockTeamCredentialStoreMockRecorder) ListExpiringEnrollments(ctx, teamID, before, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiringEnrollments", reflect.TypeOf((*MockTeamCredentialStore)(nil).ListExpiringEnrollments), ctx, teamID, before, limit)
}

// ListOwnedCredentials mocks base method.
func (m *MockTeamCredentialStore) ListOwnedCredentials(ctx context.Context, teamID, membershipID, agentID string, filter onprem.AgentArtifactFilter, now time.Time) ([]onprem.AgentCredentialMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOwnedCredentials", ctx, teamID, membershipID, agentID, filter, now)
	ret0, _ := ret[0].([]onprem.AgentCredentialMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOwnedCredentials indicates an expected call of ListOwnedCredentials.
func (mr *MockTeamCredentialStoreMockRecorder) ListOwnedCredentials(ctx, teamID, membershipID, agentID, filter, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOwnedCredentials", reflect.TypeOf((*MockTeamCredentialStore)(nil).ListOwnedCredentials), ctx, teamID, membershipID, agentID, filter, now)
}

// ListOwnedEnrollments mocks base method.
func (m *MockTeamCredentialStore) ListOwnedEnrollments(ctx context.Context, teamID, membershipID, agentID string, filter onprem.AgentArtifactFilter, now time.Time) ([]onprem.AgentEnrollmentMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOwnedEnrollments", ctx, teamID, membershipID, agentID, filter, now)
	ret0, _ := ret[0].([]onprem.AgentEnrollmentMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOwnedEnrollments indicates an expected call of ListOwnedEnrollments.
func (mr *MockTeamCredentialStoreMockRecorder) ListOwnedEnrollments(ctx, teamID, membershipID, agentID, filter, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOwnedEnrollments", reflect.TypeOf((*MockTeamCredentialStore)(nil).ListOwnedEnrollments), ctx, teamID, membershipID, agentID, filter, now)
}

// ProvisionAgentCredential mocks base method.
func (m *MockTeamCredentialStore) ProvisionAgentCredential(ctx context.Context, teamID, deviceCredentialID string, profile onprem.AgentProfile, credential onprem.CredentialRecord, activeAgentLimit int, now time.Time) (onprem.ProvisionOutcome, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionAgentCredential", ctx, teamID, deviceCredentialID, profile, credential, activeAgentLimit, now)
	ret0, _ := ret[0].(onprem.ProvisionOutcome)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvisionAgentCredential indicates an expected call of ProvisionAgentCredential.
func (mr *MockTeamCredentialStoreMockRecorder) ProvisionAgentCredential(ctx, teamID, deviceCredentialID, profile, credential, activeAgentLimit, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionAgentCredential", reflect.TypeOf((*MockTeamCredentialStore)(nil).ProvisionAgentCredential), ctx, teamID, deviceCredentialID, profile, credential, activeAgentLimit, now)
}

// ResolveCredential mocks base method.
func (m *MockTeamCredentialStore) ResolveCredential(ctx context.Context, credentialID string, digest onprem.Digest, now time.Time) (saas.ScopedCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveCredential", ctx, credentialID, digest, now)
	ret0, _ := ret[0].(saas.ScopedCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveCredential indicates an expected call of ResolveCredential.
func (mr *MockTeamCredentialStoreMockRecorder) ResolveCredential(ctx, credentialID, digest, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveCredential", reflect.TypeOf((*MockTeamCredentialStore)(nil).ResolveCredential), ctx, credentialID, digest, now)
}

// RevokeDevice mocks base method.
func (m *MockTeamCredentialStore) RevokeDevice(ctx context.Context, teamID string, actor onprem.HumanPrincipal, credentialID, idempotencyKey string, now time.Time) (onprem.DeviceSummary, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeDevice", ctx, teamID, actor, credentialID, idempotencyKey, now)
	ret0, _ := ret[0].(onprem.DeviceSummary)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeDevice indicates an expected call of RevokeDevice.
func (mr *MockTeamCredentialStoreMockRecorder) RevokeDevice(ctx, teamID, actor, credentialID, idempotencyKey, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeDevice", reflect.TypeOf((*MockTeamCredentialStore)(nil).RevokeDevice), ctx, teamID, actor, credentialID, idempotencyKey, now)
}

// RevokeOwnedCredential mocks base method.
func (m *MockTeamCredentialStore) RevokeOwnedCredential(ctx context.Context, teamID, membershipID string, actor onprem.HumanPrincipal, agentID, credentialID, idempotencyKey string, now time.Time) (onprem.AgentCredentialMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeOwnedCredential", ctx, teamID, membershipID, actor, agentID, credentialID, idempotencyKey, now)
	ret0, _ := ret[0].(onprem.AgentCredentialMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeOwnedCredential indicates an expected call of RevokeOwnedCredential.
func (mr *MockTeamCredentialStoreMockRecorder) RevokeOwnedCredential(ctx, teamID, membershipID, actor, agentID, credentialID, idempotencyKey, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeOwnedCredential", reflect.TypeOf((*MockTeamCredentialStore)(nil).RevokeOwnedCredential), ctx, teamID, membershipID, actor, agentID, credentialID, idempotencyKey, now)
}

// RevokeOwnedEnrollment mocks base method.
func (m *MockTeamCredentialStore) RevokeOwnedEnrollment(ctx context.Context, teamID, membershipID string, actor onprem.HumanPrincipal, agentID, enrollmentID, idempotencyKey string, now time.Time) (onprem.AgentEnrollmentMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeOwnedEnrollment", ctx, teamID, membershipID, actor, agentID, enrollmentID, idempotencyKey, now)
	ret0, _ := ret[0].(onprem.AgentEnrollmentMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevokeOwnedEnrollment indicates an expected call of RevokeOwnedEnrollment.
func (mr *MockTeamCredentialStoreMockRecorder) RevokeOwnedEnrollment(ctx, teamID, membershipID, actor, agentID, enrollmentID, idempotencyKey, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeOwnedEnrollment", reflect.TypeOf((*MockTeamCredentialStore)(nil).RevokeOwnedEnrollment), ctx, teamID, membershipID, actor, agentID, enrollmentID, idempotencyKey, now)
}

// RotateCredential mocks base method.
func (m *MockTeamCredentialStore) RotateCredential(ctx context.Context, teamID, currentID string, replacement onprem.CredentialRecord, overlapUntil time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateCredential", ctx, teamID, currentID, replacement, overlapUntil)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateCredential indicates an expected call of RotateCredential.
func (mr *MockTeamCredentialStoreMockRecorder) RotateCredential(ctx, teamID, currentID, replacement, overlapUntil any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateCredential", reflect.TypeOf((*MockTeamCredentialStore)(nil).RotateCredential), ctx, teamID, currentID, replacement, overlapUntil)
}
