// Code generated by hertz generator.

package httpapi

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/pax-beehive/pax-nexus/internal/todoapp/transport/httpapi/model/todoapp/api"
)

// CompleteTodo .
// @router /v1/todo/todos/:todo_id/complete [POST]
func CompleteTodo(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "Todo App handler is not configured")
		return
	}
	var req api.TodoByIDRequest
	if err := c.BindAndValidate(&req); err != nil {
		writeBindingError(c, err)
		return
	}
	handler.CompleteTodo(ctx, c, &req)
}
