// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/runtime.go -package=mocks Runtime
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	teamnote "github.com/pax-beehive/pax-nexus/internal/teamnote"
	gomock "go.uber.org/mock/gomock"
)

// MockRuntime is a mock of Runtime interface.
type MockRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeMockRecorder
	isgomock struct{}
}

// MockRuntimeMockRecorder is the mock recorder for MockRuntime.
type MockRuntimeMockRecorder struct {
	mock *MockRuntime
}

// NewMockRuntime creates a new mock instance.
func NewMockRuntime(ctrl *gomock.Controller) *MockRuntime {
	mock := &MockRuntime{ctrl: ctrl}
	mock.recorder = &MockRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntime) EXPECT() *MockRuntimeMockRecorder {
	return m.recorder
}

// ObserveSession mocks base method.
func (m *MockRuntime) ObserveSession(arg0 context.Context, arg1 teamnote.SessionBatch) (teamnote.IngestReceipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ObserveSession", arg0, arg1)
	ret0, _ := ret[0].(teamnote.IngestReceipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ObserveSession indicates an expected call of ObserveSession.
func (mr *MockRuntimeMockRecorder) ObserveSession(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveSession", reflect.TypeOf((*MockRuntime)(nil).ObserveSession), arg0, arg1)
}

// RecallNotes mocks base method.
func (m *MockRuntime) RecallNotes(arg0 context.Context, arg1 teamnote.RecallRequest) (teamnote.NoteEnvelope, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecallNotes", arg0, arg1)
	ret0, _ := ret[0].(teamnote.NoteEnvelope)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecallNotes indicates an expected call of RecallNotes.
func (mr *MockRuntimeMockRecorder) RecallNotes(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecallNotes", reflect.TypeOf((*MockRuntime)(nil).RecallNotes), arg0, arg1)
}
