// Code generated by hertz generator.

package httpapi

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/pax-beehive/pax-nexus/internal/pagewiki/transport/httpapi/model/pagewiki/api"
)

// GetNavigation .
// @router /v1/wiki/navigation [GET]
func GetNavigation(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "Page Wiki handler is not configured")
		return
	}
	var req api.NavigationRequest
	if err := c.BindAndValidate(&req); err != nil {
		writeBindingError(c, err)
		return
	}
	handler.GetNavigation(ctx, c)
}
