// Code generated by hertz generator.

package httpapi

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/pax-beehive/pax-nexus/internal/pagewiki/transport/httpapi/model/pagewiki/api"
)

// GetSourceBacklinks .
// @router /sources/:revision/backlinks [GET]
func GetSourceBacklinks(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "Page Wiki handler is not configured")
		return
	}
	var req api.SourceRevisionRequest
	if err := c.BindAndValidate(&req); err != nil {
		writeBindingError(c, err)
		return
	}
	handler.GetSourceBacklinks(ctx, c, &req)
}
