// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getnavigationMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _searchMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _filesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _injectfileMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _maintenanceMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _runsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getmaintenancerunMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _pagesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpageMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _slugMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpagebacklinksMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listpagerevisionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revisionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getpagerevisionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sessionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _injectsessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sourcesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsourcerevisionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _revisionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _getsourcebacklinksMw() []app.HandlerFunc {
	// your code...
	return nil
}
