// Code generated by MockGen. DO NOT EDIT.
// Source: contracts.go
//
// Generated by this command:
//
//	mockgen -source=contracts.go -destination=mocks/query.go -package=mocks Query
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	audit "github.com/pax-beehive/pax-nexus/internal/audit"
	gomock "go.uber.org/mock/gomock"
)

// MockQuery is a mock of Query interface.
type MockQuery struct {
	ctrl     *gomock.Controller
	recorder *MockQueryMockRecorder
	isgomock struct{}
}

// MockQueryMockRecorder is the mock recorder for MockQuery.
type MockQueryMockRecorder struct {
	mock *MockQuery
}

// NewMockQuery creates a new mock instance.
func NewMockQuery(ctrl *gomock.Controller) *MockQuery {
	mock := &MockQuery{ctrl: ctrl}
	mock.recorder = &MockQueryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuery) EXPECT() *MockQueryMockRecorder {
	return m.recorder
}

// GetActivityDaily mocks base method.
func (m *MockQuery) GetActivityDaily(arg0 context.Context, arg1 audit.ActivityFilter) ([]audit.ActivityDaily, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActivityDaily", arg0, arg1)
	ret0, _ := ret[0].([]audit.ActivityDaily)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActivityDaily indicates an expected call of GetActivityDaily.
func (mr *MockQueryMockRecorder) GetActivityDaily(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActivityDaily", reflect.TypeOf((*MockQuery)(nil).GetActivityDaily), arg0, arg1)
}

// ListFindings mocks base method.
func (m *MockQuery) ListFindings(arg0 context.Context, arg1 audit.FindingFilter) ([]audit.Finding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFindings", arg0, arg1)
	ret0, _ := ret[0].([]audit.Finding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFindings indicates an expected call of ListFindings.
func (mr *MockQueryMockRecorder) ListFindings(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFindings", reflect.TypeOf((*MockQuery)(nil).ListFindings), arg0, arg1)
}

// ListToolCalls mocks base method.
func (m *MockQuery) ListToolCalls(arg0 context.Context, arg1 audit.ToolCallFilter) ([]audit.ToolCall, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListToolCalls", arg0, arg1)
	ret0, _ := ret[0].([]audit.ToolCall)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListToolCalls indicates an expected call of ListToolCalls.
func (mr *MockQueryMockRecorder) ListToolCalls(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListToolCalls", reflect.TypeOf((*MockQuery)(nil).ListToolCalls), arg0, arg1)
}
