// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ArchiveChannelEnvelope .
// @router /v1/channel/envelopes/:envelope_id/archive [POST]
func ArchiveChannelEnvelope(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	handler.ArchiveChannelEnvelope(ctx, c)
}
