// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// BeginHumanLogin .
// @router /v1/auth/login [GET]
func BeginHumanLogin(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	handler.BeginHumanLogin(ctx, c)
}
