// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ExchangeAgentEnrollment .
// @router /v1/agent-enrollments/exchange [POST]
func ExchangeAgentEnrollment(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	handler.ExchangeAgentEnrollment(ctx, c)
}
