// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetMember .
// @router /v1/admin/members/:membership_id [GET]
func GetMember(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	handler.GetMember(ctx, c)
}
