// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	api "github.com/pax-beehive/pax-nexus/internal/teamnote/transport/httpapi/model/teammemory/api"
)

// GetOverview .
// @router /v1/admin/overview [GET]
func GetOverview(ctx context.Context, c *app.RequestContext) {
	var err error
	var req api.OverviewRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(api.OverviewResponse)

	c.JSON(consts.StatusOK, resp)
}
