// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetExtractionDiagnostic .
// @router /v1/admin/diagnostics/extractions/:run_id [GET]
func GetExtractionDiagnostic(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	handler.GetExtractionDiagnostic(ctx, c)
}
