// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// GetChannelDiagnostic .
// @router /v1/admin/diagnostics/channels/:envelope_id [GET]
func GetChannelDiagnostic(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	handler.GetChannelDiagnostic(ctx, c)
}
