// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// ListSessionAuditFindings .
// @router /v1/admin/session-audit/findings [GET]
func ListSessionAuditFindings(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	handler.ListSessionAuditFindings(ctx, c)
}
