// Code generated by hertz generator.

package handler

import (
	"context"
	"errors"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/pax-beehive/pax-nexus/internal/teamnote"
	api "github.com/pax-beehive/pax-nexus/internal/teamnote/transport/httpapi/model/teammemory/api"
)

// ObserveSession .
// @router /v1/session-batches [POST]
func ObserveSession(ctx context.Context, c *app.RequestContext) {
	startedAt := time.Now()
	deps, err := currentDependencies()
	if err != nil {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	var req api.SessionBatch
	if err := c.BindAndValidate(&req); err != nil {
		deps.logger.WarnContext(ctx, "session batch rejected", "stage", "bind", "error", err)
		c.String(consts.StatusBadRequest, "invalid session batch")
		return
	}
	scopeID, err := deps.resolver.ResolveScope(c)
	if errors.Is(err, ErrUnauthorized) {
		deps.logger.WarnContext(ctx, "session batch rejected", "stage", "authorize")
		c.String(consts.StatusUnauthorized, "unauthorized")
		return
	}
	if err != nil {
		deps.logger.ErrorContext(ctx, "resolve session scope failed", "error", err)
		c.String(consts.StatusInternalServerError, "resolve scope")
		return
	}
	batch, err := sessionBatchToDomain(&req)
	if err != nil {
		deps.logger.WarnContext(ctx, "session batch rejected", "stage", "map", "error", err)
		c.String(consts.StatusBadRequest, "invalid session batch")
		return
	}
	receipt, err := deps.runtime.ObserveSession(teamnote.WithScope(ctx, scopeID), batch)
	if err != nil {
		deps.logger.ErrorContext(ctx, "observe session failed", "scope_id", scopeID, "error", err)
		c.String(consts.StatusUnprocessableEntity, "observe session")
		return
	}
	actor := batch.Events[0].Actor
	deps.logger.InfoContext(ctx, "session batch observed",
		"scope_id", scopeID, "user_id", actor.UserID, "agent_id", actor.AgentID, "session_id", actor.SessionID,
		"events", len(batch.Events), "accepted", receipt.Accepted, "duplicates", receipt.Duplicate,
		"cursor", receipt.Cursor, "run_id", receipt.RunID, "duration_ms", time.Since(startedAt).Milliseconds(),
	)
	c.JSON(consts.StatusOK, ingestReceiptToAPI(receipt))
}
