// Code generated by hertz generator.

package handler

import (
	"context"
	"errors"
	"time"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/pax-beehive/pax-nexus/internal/teamnote"
	api "github.com/pax-beehive/pax-nexus/internal/teamnote/transport/httpapi/model/teammemory/api"
)

// RecallNotes .
// @router /v1/notes/recall [POST]
func RecallNotes(ctx context.Context, c *app.RequestContext) {
	startedAt := time.Now()
	deps, err := currentDependencies()
	if err != nil {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	var req api.RecallRequest
	if err := c.BindAndValidate(&req); err != nil {
		deps.logger.WarnContext(ctx, "recall request rejected", "stage", "bind", "error", err)
		c.String(consts.StatusBadRequest, "invalid recall request")
		return
	}
	scopeID, err := deps.resolver.ResolveScope(c)
	if errors.Is(err, ErrUnauthorized) {
		deps.logger.WarnContext(ctx, "recall request rejected", "stage", "authorize")
		c.String(consts.StatusUnauthorized, "unauthorized")
		return
	}
	if err != nil {
		deps.logger.ErrorContext(ctx, "resolve recall scope failed", "error", err)
		c.String(consts.StatusInternalServerError, "resolve scope")
		return
	}
	request, err := recallRequestToDomain(&req)
	if err != nil {
		deps.logger.WarnContext(ctx, "recall request rejected", "stage", "map", "error", err)
		c.String(consts.StatusBadRequest, "invalid recall request")
		return
	}
	envelope, err := deps.runtime.RecallNotes(teamnote.WithScope(ctx, scopeID), request)
	if err != nil {
		deps.logger.ErrorContext(ctx, "recall notes failed", "scope_id", scopeID, "user_id", request.Actor.UserID,
			"agent_id", request.Actor.AgentID, "session_id", request.Actor.SessionID, "error", err)
		c.String(consts.StatusUnprocessableEntity, "recall notes")
		return
	}
	deps.logger.InfoContext(ctx, "team notes recalled",
		"scope_id", scopeID, "user_id", request.Actor.UserID, "agent_id", request.Actor.AgentID,
		"session_id", request.Actor.SessionID, "notes", len(envelope.Details), "tokens", envelope.Tokens,
		"duration_ms", time.Since(startedAt).Milliseconds(),
	)
	c.JSON(consts.StatusOK, noteEnvelopeToAPI(envelope))
}
