// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// RetireOwnedAgent .
// @router /v1/me/agents/:agent_id [DELETE]
func RetireOwnedAgent(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	handler.RetireOwnedAgent(ctx, c)
}
