// Code generated by hertz generator.

package handler

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// TransferAdminAgent .
// @router /v1/admin/agents/:agent_id/transfer [POST]
func TransferAdminAgent(ctx context.Context, c *app.RequestContext) {
	handler, ok := handlerFromRequest(c)
	if !ok {
		c.String(consts.StatusInternalServerError, "runtime is not configured")
		return
	}
	handler.TransferAdminAgent(ctx, c)
}
