// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _todoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtodosuggestionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listtodosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createtodoMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _suggestionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _refreshtodosuggestionsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _suggestion_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _accepttodosuggestionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _dismisstodosuggestionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _todosMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _todo_idMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _completetodoMw() []app.HandlerFunc {
	// your code...
	return nil
}
