// Code generated by hertz generator.

package api

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _healthMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _observesessionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _notesMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _recallnotesMw() []app.HandlerFunc {
	// your code...
	return nil
}
