#!/bin/sh
set -eu

minimum="${COVERAGE_MIN:-75}"
output_dir=".build"
raw_profile="${output_dir}/coverage.raw.out"
profile="${output_dir}/coverage.out"
generated_handler_files="$(rg -l '^// Code generated by hertz generator' internal/teamnote/transport/httpapi/handler --glob '*.go' | paste -sd, -)"

mkdir -p "${output_dir}"
go test ./... -count=1 -covermode=atomic -coverprofile="${raw_profile}"

awk -v generated_handler_files="${generated_handler_files}" '
BEGIN { generated_count = split(generated_handler_files, generated_files, ",") }
function is_generated_handler(path, index_value) {
  for (index_value = 1; index_value <= generated_count; index_value++) {
    if (generated_files[index_value] != "" && index(path, "/" generated_files[index_value] ":") > 0) {
      return 1
    }
  }
  return 0
}
NR == 1 { print; next }
$1 !~ /\/internal\/teamnote\/transport\/httpapi\/(model|router)\// &&
$1 !~ /\/internal\/platform\/postgres\// && $1 !~ /\/internal\/eval\/v2\/postgresstore\// && $1 !~ /\/mocks\// &&
$1 !~ /\/cmd\// && $1 !~ /\.gen\.go:/ && !is_generated_handler($1) { print }
' "${raw_profile}" > "${profile}"

total="$(go tool cover -func="${profile}" | awk '/^total:/ { gsub("%", "", $3); print $3 }')"
if [ -z "${total}" ]; then
  echo "unable to calculate unit-test coverage" >&2
  exit 1
fi

awk -v total="${total}" -v minimum="${minimum}" 'BEGIN {
  if (total + 0 < minimum + 0) {
    printf "unit-test coverage %.1f%% is below %.1f%%\n", total, minimum > "/dev/stderr"
    exit 1
  }
  printf "unit-test coverage %.1f%% meets %.1f%% threshold\n", total, minimum
}'
