// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	pagewiki_api "github.com/pax-beehive/pax-nexus/internal/teamnote/transport/httpapi/router/pagewiki/api"
	teammemory_api "github.com/pax-beehive/pax-nexus/internal/teamnote/transport/httpapi/router/teammemory/api"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	pagewiki_api.Register(r)

	teammemory_api.Register(r)
}
